#!/usr/bin/env bash
#
# blkfree
#   show mountpoint and free megabytes of files/dirs from $@
#
# scott@smemsh.net
# https://github.com/smemsh/utilsh/
# https://spdx.org/licenses/GPL-2.0
#

bydf () { df -B1 $1 | tail -n +2 | awk '{print $4, $NF}'; }
byfindmnt () { findmnt -nbT $1 -o target,avail; }
findmnt --help |& grep -qw -- --bytes && cmd=byfindmnt || cmd=bydf

for arg; do
read diskfree mntpt < <($cmd $arg)
echo $mntpt $((diskfree >> 20))
done
