#!/bin/bash
#
# fflatest
#   find latest regular file in dirtree by mtime, print parseable mtime stdout
#
# todo
#   - allow other kinds of times to be tested
#   - make sure this will handle filenames with newlines
#   - flags to print the name, the date, or both
#   - handle other kinds of inodes besides regular files
#
# https://github.com/smemsh/utilsh/
# http://spdx.org/licenses/GPL-2.0
# scott@smemsh.net
#
##############################################################################

if [[ $1 =~ [[:digit:]] && $2 ]]
then howmany=$1; shift; fi

dir="$1"
test -d "$dir" || exit

find "$dir"/ -type f -printf '%TY%Tm%Td%TH%TM%TS:%p\n' \
| sort -nr -t . -k 1,2 \
| awk -F : '{print substr($1, 0, index($1, ".") - 1)}' \
| head -${howmany:-'1'}
