#!/bin/bash
#
# mk4group
#   - makes directories setgid-group, recursively
#   - mode bits are copied from user to group
#
# args
#   - system group given as $1
#   - all remaining args: trees to be recursively converted
#
# scott@smemsh.net
# http://smemsh.net/utilsh/
# http://spdx.org/licenses/GPL-2.0.html
#
##############################################################################

bomb ()
{
	echo "$@" >&2
	exit 1
}

###

dirtree_setgid_on_dirs ()
{
	local dir=$1
	find $dir/ -type d -print0 \
	| xargs -r0 chmod g+s
}

dirtree_change_group ()
{
	local grp=$1
	local dir=$2
	chgrp -R $grp $dir/
}

dirtree_user2group_baseperm ()
{
	local dir=$1

	getfacl --recursive --access $dir |
	sed -e '
		/^user:/ { h; b; }			# hold onto user perms
		/^group:/ { x; s/^user:/group:/; b; }	# group becomes held
	' |
	setfacl --restore=-
}

##############################################################################

main ()
{
	local group=$1; shift

	gid=$(getent group $group | awk -F : '{print $(NF-1)}')
	[[ $gid ]] || bomb "group $group does not look up"

	for ((i = 1; i <= $#; i++)); do
		dir=${!i}
		test -d $dir
		test -w $dir
		cd $dir/..
		dirtree_change_group $gid $dir
		dirtree_setgid_on_dirs $dir
		dirtree_user2group_baseperm ${dir##*/}
	done
}

###

set -e
main "$@"
