#!/bin/bash
#
# mk4group
#   recursively makes dirs group-owned, setgid, and copies user mode to group
#
# args:
#   - system group to chgrp given as $1
#   - all remaining args: trees to be recursively converted
#
# scott@smemsh.net
# https://github.com/smemsh/utilsh/
# https://spdx.org/licenses/GPL-2.0
#
##############################################################################

bomb ()
{
	echo "$@" >&2
	exit 1
}

###

dirtree_setgid_on_dirs ()
{
	local dir=$1
	find "$dir" -type d -print0 \
	| xargs -r0 chmod g+s
}

dirtree_change_group ()
{
	local grp=$1
	local dir="$2"
	chgrp -R $grp "$dir"
}

dirtree_user2group_permcopy ()
{
	local dir="$1"
	local permbit

	for permbit in 4 2 1
	do
		find "$dir" \
			-not -type l \
			-perm -0${permbit}00 \
			-print0 \
		| xargs -r0 chmod +00${permbit}0
	done
}

##############################################################################

main ()
{
	local group=$1; shift
	local gid dir path

	gid=$(getent group $group | awk -F : '{print $(NF-1)}')
	if ! [[ $gid ]]; then
		bomb "group $group does not look up"; fi

	for ((i = 1; i <= $#; i++))
	do
		dir="${!i}"
		path=$(readlink -e "$dir")

		test -d "$path" ||
			bomb "path '$path' dne"

		test -w "$path" ||
			bomb "path '$path' not writable"

		dirtree_change_group $gid "$path" ||
			bomb "chrgrp failed"

		dirtree_setgid_on_dirs "$path" ||
			bomb "setgid failed"

		dirtree_user2group_permcopy "$path" ||
			bomb "perms copy failed"
	done
}

###

main "$@"
