#!/usr/bin/env bash
#
# debian removed rename.ul from its util-linux installation, so we have to
# write our own, sadly.  while we're at it, we add a couple options to make it
# easier to to prepend or append something without needing empty string
# argument (which only works to append), although we still take that to keep
# the interface
#
# cf https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982944
#

eval set -- $(getopt -n "${0##*/}" \
-o hp:a: \
-l help,prepend:,append: \
-- "$@")
while true; do case $1 in
(-p|--prepend) prepend="$2"; shift 2;;
(-a|--append) append="$2"; shift 2;;
(-h|--help) cat <<-%
	-p/--prepend <string to add to beginning>
	-a/--append <string to add to end>
	%
	echo "read script for more usage" >&2; false; exit;;
(--) shift; break;;
(*) echo "impossible condition" >&2; false; exit;;
esac; done

###

if [[ $prepend && $append ]]
then echo "cannot both prepend and append" >&2; false; exit
elif [[ $append ]]; then to="$append"
elif [[ $prepend ]]; then :
else from="$1"; to="$2"; shift 2
fi

for file
do
	if [[ $file == '.' || $file == '..' ]]
	then echo "skipping '$file'" >&2; continue; fi

	if [[ $file =~ '/' ]]
	then echo "skipping path '$file'" >&2; continue; fi

	if [[ $prepend ]]; then newname="$prepend$file"
	elif [[ $from == '' || $append ]]; then newname="$file$to"
	else newname="${file/$from/$to}"
	fi
	mv "$file" "$newname"
done
