#!/usr/bin/env bash
#
# srcdirs
#   all git repos in $1 with config attribute $2 == 'true' printed
#
# note:
#   - does not handle spaces in repo paths (and newline is OFS)
#   - works only with non-bare repositories
#   - default basedir ~/src
#   - default pubattr 'srcdirs.ispublic'
#
# scott@smemsh.net
# https://github.com/smemsh/utilsh/
# https://spdx.org/licenses/GPL-2.0
#
##############################################################################

basedir=${1:-~/src}
pubattr=${2:-'srcdirs.ispublic'}

for dir in $(
	find $basedir/ \
	-mindepth 2 \
	-maxdepth 2 \
	-type d \
	-name '.git' \
); do
	basedir=${dir%.git}
	basedir=${basedir%/}
	ispublic=$(git -C $basedir config --get --bool $pubattr)
	[[ $ispublic == 'true' ]] &&
		echo "$basedir"
done

true
