#!/bin/bash
#
# trunc
#   wraps coreutils 'truncate', making all args zero bytes
#
# args:
#   - any options and files to give to 'truncate'
#
# scott@smemsh.net
# https://github.com/smemsh/utilsh/
# https://spdx.org/licenses/GPL-2.0

truncate --size=0 "$@"
