#!/usr/bin/env bash

invname=${0##*/}
[[ $invname == vimver ]] && let ++vercmd

((vercmd)) && set -- echon v:versionlong

vim -u NONE -e \
--cmd 'redir! > /dev/stdout' \
--cmd "$*" \
--cmd quit \
-s \
</dev/null

((vercmd)) && tty -s && echo || true
